spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: travelwithme.mail@gmail.com
    password: puofrxedultxqtul
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

  data:
    redis:
      host: localhost
      port: 6379



jwt:
  issuer: hs1j333@gmail.com
  secret_key: prototype
